# Generated by Django 5.2.5 on 2026-01-09 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('desc', models.TextField(max_length=500)),
                ('phonenumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('subcategory', models.CharField(default='', max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('desc', models.TextField(max_length=500)),
                ('product_image', models.ImageField(default='images/placeholder.png', upload_to='images')),
                ('size', models.CharField(default='', max_length=50)),
                ('plant_type', models.CharField(default='', max_length=50)),
                ('thc', models.CharField(default='', max_length=50)),
                ('cbd', models.CharField(default='', max_length=50)),
                ('effects', models.CharField(default='', max_length=200)),
                ('tags', models.CharField(default='', max_length=100)),
                ('sku', models.CharField(default='', max_length=50)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='herbalapp.category')),
            ],
        ),
    ]
